# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-14 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20180814_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinepositionprefix',
            options={'ordering': ('pk',)},
        ),
    ]
