# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=13)),
                ('bestand', models.IntegerField(blank=True, max_length=25, null=True)),
                ('sku', models.IntegerField(blank=True, max_length=25, null=True)),
                ('place', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('scanner', models.IntegerField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('carton', models.CharField(blank=True, max_length=25, null=True)),
                ('box', models.IntegerField(blank=True, max_length=25, null=True)),
                ('area', models.CharField(blank=True, max_length=25, null=True)),
                ('checked', models.CharField(blank=True, max_length=25, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
