# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0002_stocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
