# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180104_0540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stocklist',
            new_name='Stockdocument',
        ),
    ]
