# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0004_auto_20180104_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdocument',
            name='uploaded_at',
        ),
    ]
