# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0005_remove_stockdocument_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
