# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-06 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0006_stockdocument_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
