# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-06 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
