# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-06 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0009_auto_20180106_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='area',
            new_name='aufnahme_datum',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='carton',
            new_name='bereich',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='sku',
            new_name='ean_upc',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='checked',
            new_name='karton',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='lagerplatz',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='place',
            new_name='ueberpruefung',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='state',
            new_name='zustand',
        ),
    ]
