# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-06 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock', '0013_auto_20180106_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
