# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_remove_stock_bereich'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ignore_unique',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
