# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20180123_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='aufnahme_datum',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Aufnahme Datum'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bestand',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bestand'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='box',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Box'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ean_vollstaendig',
            field=models.CharField(max_length=250, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='karton',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Karton'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lagerplatz',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Lagerplatz'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='regal',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Regal'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='scanner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Scanner'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='zustand',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Zustand'),
        ),
    ]
