# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20180321_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sku',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sku'),
        ),
        migrations.AddField(
            model_name='stock',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Artikelname'),
        ),
    ]
