# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
