# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_auto_20180408_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.CharField(blank=True, max_length=250, null=True, verbose_name='Regal')),
                ('level', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ebene')),
                ('column', models.CharField(blank=True, max_length=250, null=True, verbose_name='Spalte')),
                ('prefix', models.CharField(blank=True, max_length=250, null=True, verbose_name='Prefix')),
            ],
        ),
    ]
