# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_delete_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sku',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Sku'),
        ),
        migrations.AddField(
            model_name='stock',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Artikelname'),
        ),
    ]
