# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['prefix', 'shelf', 'level', 'column']},
        ),
        migrations.AlterField(
            model_name='position',
            name='column',
            field=models.IntegerField(blank=True, verbose_name='Spalte'),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.IntegerField(blank=True, verbose_name='Ebene'),
        ),
        migrations.AlterField(
            model_name='position',
            name='shelf',
            field=models.IntegerField(blank=True, verbose_name='Regal'),
        ),
    ]
