# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_stock_missing_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='missing_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fehlender Bestand'),
        ),
    ]
