# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_auto_20180617_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Position'),
        ),
    ]
