# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-08 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0010_auto_20180516_1025'),
        ('stock', '0038_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sku_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.Sku', verbose_name='Sku Instanz'),
        ),
    ]
