# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_stock_sku_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-pk']},
        ),
    ]
