# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-28 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_rebookorder_rebookorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebookorder',
            name='all_rebooked',
            field=models.NullBooleanField(verbose_name='Alles umgebucht'),
        ),
        migrations.AlterField(
            model_name='rebookorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Umbucher'),
        ),
    ]
