# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0044_auto_20181130_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebookorderitem',
            name='destination_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='stock.Stock', verbose_name='Bestand'),
        ),
    ]
