# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0046_rebookorderitem_rebooked_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebookOrderItemDestinationStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebooked_amount', models.IntegerField(blank=True, null=True, verbose_name='Tatsächliche Umbuchmenge')),
                ('rebook_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.RebookOrderItem')),
            ],
        ),
    ]
