# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-02 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_auto_20181201_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebookorderitem',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Stock', verbose_name='Bestand'),
        ),
        migrations.AlterField(
            model_name='rebookorderitemdestinationstock',
            name='destination_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='stock.Stock', verbose_name='Bestand'),
        ),
    ]
