# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0049_auto_20181202_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebookorderitem',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ausgangslagerplatz'),
        ),
        migrations.AddField(
            model_name='rebookorderitemdestinationstock',
            name='destination_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endlagerplatz'),
        ),
    ]
