# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-02 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0015_auto_20181107_2310'),
        ('stock', '0050_auto_20181202_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebookorderitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sku.Sku'),
        ),
        migrations.AddField(
            model_name='rebookorderitemdestinationstock',
            name='destination_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sku.Sku'),
        ),
    ]
