# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0051_auto_20181202_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebookorder',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rebookorder',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
