# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ort_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='strasse',
        ),
    ]
