# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20171230_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='client',
            name='telefon',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
