# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20171230_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telefon',
        ),
    ]
