# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('client', '0004_auto_20171230_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='contact.Contact'),
        ),
    ]
