# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-23 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
