# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20180423_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR-Code'),
        ),
    ]
