# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-10 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('access_key_encrypted', models.CharField(blank=True, max_length=400, null=True)),
                ('secret_key_encrypted', models.CharField(blank=True, max_length=400, null=True)),
                ('account_id_encrypted', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
