# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-10 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_apidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='api_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.ApiData'),
        ),
    ]
