# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_api_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='api_data',
        ),
        migrations.AddField(
            model_name='apidata',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='access_key_encrypted',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Access Key'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='account_id_encrypted',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='secret_key_encrypted',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Secret Key'),
        ),
    ]
