# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20180811_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Client', verbose_name='Mandant'),
        ),
    ]
