# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-31 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20180831_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='access_token',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Zugriffstoken'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Aktualisierungstoken'),
        ),
    ]
