version: '3'
services:
  db:
    image: postgres
  redis:
    image: "redis:3.2.12"
    ports:
      - '6379:6379'
  web:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/erpghost
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    tty: true
    command: celery -A erpghost worker -l info
    volumes:
      - .:/erpghost
    depends_on:
      - db
      - redis
  online_cronjob:
    build: .
    tty: true
    command: bash -c "python manage.py online_cronjob"
    volumes:
      - .:/erpghost
