# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='truck',
        ),
    ]
