# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0071_auto_20180628_0304'),
        ('disposition', '0002_auto_20180628_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='truck',
            field=models.ManyToManyField(to='mission.Truck'),
        ),
    ]
