# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0003_employee_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='truck',
            field=models.ManyToManyField(related_name='employees', to='mission.Truck'),
        ),
    ]
