# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-07 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0093_auto_20180706_1932'),
        ('disposition', '0007_auto_20180628_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Ankunftsdatum')),
                ('arrival_time_start', models.TimeField(blank=True, null=True, verbose_name='Ankunftszeit von')),
                ('arrival_time_end', models.TimeField(blank=True, null=True, verbose_name='Ankunftszeit bis')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Truck')),
            ],
        ),
    ]
