# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-07 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0008_truckappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckappointment',
            name='employees',
            field=models.ManyToManyField(blank=True, to='disposition.Employee'),
        ),
    ]
