# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0011_auto_20180707_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profilbild'),
        ),
    ]
