# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-09 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0013_businessaccount_transportservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='transport_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disposition.TransportService'),
        ),
    ]
