# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-10 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_qr_code'),
        ('disposition', '0015_auto_20180810_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
        migrations.AlterField(
            model_name='transportservice',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Bezeichnung'),
        ),
    ]
