# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0017_auto_20180810_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('Deutschland', 'Deutschland'), ('International', 'International')], max_length=200, null=True, verbose_name='Art'),
        ),
    ]
