# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0018_businessaccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='type',
            field=models.CharField(choices=[('national', 'Deutschland'), ('foreign_country', 'Ausland')], max_length=200, null=True, verbose_name='Art'),
        ),
    ]
