# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0019_auto_20180811_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='celery_import_task_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
