# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180328_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='contact.Contact', verbose_name='Kontaktdaten'),
        ),
    ]
