# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180328_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kunden-Nr.'),
        ),
    ]
