# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Markenname')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild')),
                ('ean', models.CharField(blank=True, max_length=200, verbose_name='EAN')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Hersteller')),
                ('brandname', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Markenname')),
                ('part_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Herstellernummer')),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Titel')),
                ('short_description', models.TextField(blank=True, default='', null=True, verbose_name='Kurzbeschreibung')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Beschreibung')),
                ('height', models.FloatField(blank=True, default=None, null=True, verbose_name='Höhe')),
                ('width', models.FloatField(blank=True, default=None, null=True, verbose_name='Breite')),
                ('length', models.FloatField(blank=True, default=None, null=True, verbose_name='Länge')),
            ],
        ),
    ]
