# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('position', '0006_auto_20171228_2347'),
        ('product', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.Position')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='positions',
            field=models.ManyToManyField(through='product.PositionProduct', to='position.Position'),
        ),
    ]
