# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20171228_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionproduct',
            name='status',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
