# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20180309_1455'),
        ('product', '0005_auto_20180124_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='supplier.Supplier', verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=13, verbose_name='EAN'),
        ),
    ]
