# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_positionproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionproduct',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
