# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180329_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Höhe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Länge'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Breite'),
        ),
    ]
