# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_sku',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU'),
        ),
    ]
