# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_main_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_sku',
            field=models.IntegerField(blank=True, null=True, verbose_name='SKU'),
        ),
    ]
