# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-25 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180516_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(blank=True, max_length=200, null=True, verbose_name='EAN')),
            ],
        ),
    ]
