# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_single_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Artikelname'),
        ),
    ]
