# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-12 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20180527_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleproduct',
            name='ean',
        ),
    ]
