# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-12 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_singleproduct_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='single_product',
            field=models.NullBooleanField(verbose_name='Einzelartikel'),
        ),
    ]
