# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20181023_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_unit',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Verpackungseinheit'),
        ),
    ]
