# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_packing_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_unit_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packing_unit_child', to='product.Product'),
        ),
    ]
