# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_api_data'),
        ('online', '0002_auto_20180714_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
