# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_client_api_data'),
        ('online', '0003_channel_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='client',
        ),
        migrations.AddField(
            model_name='channel',
            name='api_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.ApiData'),
        ),
    ]
