# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-10 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online', '0004_auto_20180811_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_order_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nachfüllauftrags ID')),
                ('completed', models.NullBooleanField(verbose_name='Erledigt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
