# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_refillorderstock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefillOrderStock',
            new_name='RefillOrderOutbookStock',
        ),
    ]
