# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-11 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_auto_20180911_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='refillorder',
            name='booked_in',
            field=models.NullBooleanField(verbose_name='Eingebucht'),
        ),
        migrations.AlterField(
            model_name='refillorder',
            name='booked_out',
            field=models.NullBooleanField(verbose_name='Ausgebucht'),
        ),
    ]
