# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-12 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20180527_0212'),
        ('online', '0011_refillorderinbookstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refillorderinbookstock',
            name='product_mission',
        ),
        migrations.AddField(
            model_name='refillorderinbookstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
