# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-12 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0012_auto_20180912_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillorderinbookstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='refillorderinbookstock',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Stock', verbose_name='Bestand'),
        ),
        migrations.AlterField(
            model_name='refillorderoutbookstock',
            name='product_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.ProductMission'),
        ),
        migrations.AlterField(
            model_name='refillorderoutbookstock',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Stock', verbose_name='Bestand'),
        ),
    ]
