# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-23 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0013_auto_20180913_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='refillorderinbookstock',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Zustand'),
        ),
    ]
