# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0014_refillorderinbookstock_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=200, null=True, verbose_name='Angebot')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Menge')),
            ],
        ),
    ]
