# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20180831_1424'),
        ('online', '0015_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Client', verbose_name='Mandant'),
        ),
    ]
