# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-24 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0016_channel_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='market',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Marktplatz'),
        ),
    ]
