# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-24 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0017_channel_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='asin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Angebot'),
        ),
    ]
