# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-26 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0013_sku_asin'),
        ('online', '0018_offer_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sku_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sku.Sku'),
        ),
    ]
