# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0021_auto_20181110_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='amount',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Menge'),
        ),
    ]
