# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='diff_kubik',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='ist_kubik',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='position',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='gesamt_kubik',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
