# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=13)),
                ('email', models.CharField(blank=True, max_length=13)),
                ('skype_id', models.CharField(blank=True, max_length=13)),
            ],
        ),
    ]
