# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20180423_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Handelsregister'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sales_tax_identification_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ust-IdNr.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tax_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Steuernummer'),
        ),
    ]
