# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-23 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20180423_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nachname'),
        ),
    ]
