# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0004_adress_place'),
        ('contact', '0007_auto_20180423_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='billing_address',
        ),
        migrations.AddField(
            model_name='contact',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact2', to='adress.Adress'),
        ),
    ]
