# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0008_auto_20180501_1848'),
        ('contact', '0009_auto_20180425_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='billing_addresses',
            field=models.ManyToManyField(related_name='billing_contact_many', to='adress.Adress', verbose_name='Zusätzliche Rechnungsadressen'),
        ),
        migrations.AddField(
            model_name='contact',
            name='delivery_addresses',
            field=models.ManyToManyField(related_name='delivery_contact_many', to='adress.Adress', verbose_name='Zusätzliche Lieferadressen'),
        ),
    ]
