# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20180501_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='website_conditions_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Webseite'),
        ),
    ]
