# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Titel'),
        ),
    ]
