# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_masterdata_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterdata', to='product.Product'),
        ),
    ]
