# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20171226_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
