# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20180329_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='short_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Titel'),
        ),
    ]
