# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-29 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20180329_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdata',
            name='product',
        ),
    ]
