# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(blank=True, default=None, null=True)),
                ('zustand', models.CharField(blank=True, max_length=13)),
                ('nettopreis', models.FloatField(blank=True, default=None, null=True)),
                ('bruttopreis', models.FloatField(blank=True, default=None, null=True)),
                ('menge', models.IntegerField(blank=True, default=None, null=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='product.Product')),
            ],
        ),
    ]
