# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='product',
        ),
    ]
