# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_remove_sku_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
