# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0003_auto_20180516_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='bruttopreis',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='menge',
        ),
    ]
