# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0004_auto_20180516_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='nettopreis',
        ),
        migrations.AddField(
            model_name='sku',
            name='purchasing_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Einkaufspreis'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='zustand',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
