# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productimage'),
        ('sku', '0005_auto_20180516_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
