# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0008_auto_20180516_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='zustand',
        ),
        migrations.AddField(
            model_name='sku',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
