# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0009_auto_20180516_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Zustand'),
        ),
    ]
