# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0010_auto_20180516_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='main_sku',
            field=models.NullBooleanField(verbose_name='Haupt-SKU'),
        ),
    ]
