# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-25 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0012_sku_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='asin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ASIN'),
        ),
    ]
