# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-07 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0013_sku_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online.Channel'),
        ),
    ]
