# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('supplier', '0002_supplier_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='contact.Contact'),
        ),
    ]
