# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_auto_20171230_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
    ]
