# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0001_initial'),
        ('supplier', '0007_remove_supplier_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='supplier', to='contact.Contact'),
        ),
    ]
