# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_auto_20180316_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=13, verbose_name='Lieferant'),
        ),
    ]
