# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0011_auto_20180316_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieferant'),
        ),
    ]
