# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0013_remove_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieferantennummer'),
        ),
    ]
