# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.CharField(blank=True, max_length=13)),
                ('level', models.CharField(blank=True, max_length=13)),
                ('place', models.CharField(blank=True, max_length=13)),
                ('halle', models.CharField(blank=True, max_length=13)),
            ],
        ),
    ]
