# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0003_product'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.Position')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
