# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0008_auto_20171227_0057'),
        ('position', '0003_position_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='column.Column')),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.Position')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='columns',
            field=models.ManyToManyField(through='position.ColumnPosition', to='column.Column'),
        ),
    ]
