# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_auto_20180328_2033'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_number', models.CharField(blank=True, max_length=13, verbose_name='Auftragsnummer')),
                ('delivery_date', models.DateField(default=datetime.date.today, verbose_name='Lieferdatum')),
                ('status', models.CharField(blank=True, default='OFFEN', max_length=25, null=True, verbose_name='Status')),
                ('pickable', models.NullBooleanField(choices=[(None, '----'), (True, 'Ja'), (False, 'Nein')], verbose_name='Pickbereit')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='customer.Customer', verbose_name='Kunde')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Menge')),
                ('missing_amount', models.IntegerField(blank=True, null=True, verbose_name='Fehlende Menge')),
                ('netto_price', models.FloatField(blank=True, null=True, verbose_name='Einzelpreis (Netto)')),
                ('confirmed', models.NullBooleanField(verbose_name='Bestätigt')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Mission', verbose_name='Auftrag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Artikel')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='products',
            field=models.ManyToManyField(through='mission.ProductMission', to='product.Product'),
        ),
    ]
