# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 23:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_number', models.CharField(max_length=13)),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
