# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20171228_2347'),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('confirmed', models.NullBooleanField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Mission')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='products',
            field=models.ManyToManyField(through='mission.ProductMission', to='product.Product'),
        ),
    ]
