# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mission', '0003_mission_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(blank=True, default='OFFEN', max_length=25, null=True),
        ),
    ]
