# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mission', '0004_auto_20180116_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='pickable',
            field=models.NullBooleanField(choices=[(None, '----'), (True, 'Ja'), (False, 'Nein')]),
        ),
    ]
