# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_mission_pickable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmission',
            name='missing_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
