# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_productmission_missing_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Lieferdatum'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='Auftragsnummer'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='pickable',
            field=models.NullBooleanField(choices=[(None, '----'), (True, 'Ja'), (False, 'Nein')], verbose_name='Pickbereit'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(blank=True, default='OFFEN', max_length=25, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='verified',
            field=models.NullBooleanField(choices=[(None, '----'), (True, 'Ja'), (False, 'Nein')], verbose_name='Akzeptiert'),
        ),
    ]
