# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('mission', '0007_auto_20180308_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='customer.Customer', verbose_name='Kunde'),
        ),
    ]
