# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0012_auto_20180316_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
