# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0004_adress_place'),
        ('mission', '0014_auto_20180426_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adress.Adress', verbose_name='Lieferadresse'),
        ),
    ]
