# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0016_auto_20180427_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='shipping',
            field=models.CharField(blank=True, choices=[('Dachser', 'Dachser'), ('DPD', 'DPD'), ('DHL', 'DHL')], max_length=200, null=True, verbose_name='Spedition'),
        ),
        migrations.AddField(
            model_name='mission',
            name='shipping_costs',
            field=models.FloatField(blank=True, max_length=200, null=True, verbose_name='Transportkosten'),
        ),
        migrations.AddField(
            model_name='mission',
            name='shipping_number_of_pieces',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stückzahl Transport'),
        ),
    ]
