# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0017_auto_20180506_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='customer_order_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bestellnummer vom Kunden'),
        ),
    ]
