# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0018_mission_customer_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_amount', models.IntegerField(blank=True, null=True)),
                ('billing_number', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_note_number', models.CharField(blank=True, max_length=200, null=True)),
                ('product_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.ProductMission')),
            ],
        ),
    ]
