# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-10 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0021_auto_20180510_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='confirmed',
            field=models.NullBooleanField(choices=[(None, '----'), (True, 'Ja'), (False, 'Nein')], verbose_name='Bestätigt'),
        ),
    ]
