# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0023_realamount_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='realamount',
            name='missing_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fehlende Menge'),
        ),
    ]
