# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-13 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0024_realamount_missing_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission', to='customer.Customer', verbose_name='Kunde'),
        ),
    ]
