# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0025_auto_20180513_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adress.Adress', verbose_name='Lieferadresse'),
        ),
    ]
