# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-18 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0026_auto_20180514_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmission',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Zustand'),
        ),
    ]
