# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0029_auto_20180527_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='missing_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fehlende Menge'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='product_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.ProductMission'),
        ),
    ]
