# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0031_auto_20180530_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteProductMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('missing_amount', models.IntegerField(blank=True, null=True, verbose_name='Fehlende Menge')),
                ('delivery_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.DeliveryNote')),
                ('product_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.ProductMission')),
            ],
        ),
    ]
