# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0032_deliverynoteproductmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='billing_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Billing'),
        ),
    ]
