# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0033_deliverynote_billing_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverynote',
            old_name='billing_number',
            new_name='billing',
        ),
    ]
