# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0037_delivery_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsIssueDeliveryMissionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Menge')),
                ('missing_amount', models.IntegerField(blank=True, null=True, verbose_name='Fehlende Menge')),
                ('delivery_mission_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.DeliveryMissionProduct')),
            ],
        ),
    ]
