# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-31 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0039_goodsissuedeliverymissionproduct_goods_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsissuedeliverymissionproduct',
            name='confirmed',
            field=models.NullBooleanField(verbose_name='Bestätigt'),
        ),
    ]
