# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-31 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0041_auto_20180531_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='goods_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.GoodsIssue'),
        ),
    ]
