# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-02 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0042_deliverynote_goods_issue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='productmission',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='deliverynoteproductmission',
            name='missing_amount',
        ),
    ]
