# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0043_auto_20180602_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='billing',
        ),
    ]
