# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0046_remove_delivery_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteproductmission',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Billing'),
        ),
    ]
