# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0048_auto_20180603_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='shipping_costs',
            field=models.FloatField(max_length=200, null=True, verbose_name='Transportkosten'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='shipping_number_of_pieces',
            field=models.IntegerField(null=True, verbose_name='Stückzahl Transport'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='transport_service',
            field=models.CharField(choices=[('Dachser', 'Dachser'), ('DPD', 'DPD'), ('DHL', 'DHL')], max_length=200, null=True, verbose_name='Transportdienstleister'),
        ),
    ]
