# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-03 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0049_auto_20180603_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.GoodsIssue')),
            ],
        ),
        migrations.AlterField(
            model_name='billing',
            name='transport_service',
            field=models.CharField(choices=[('Spedition', 'Spedition'), ('Dachser', 'Dachser'), ('DPD', 'DPD'), ('DHL', 'DHL')], max_length=200, null=True, verbose_name='Transportdienstleister'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='shipping',
            field=models.CharField(blank=True, choices=[('Spedition', 'Spedition'), ('Dachser', 'Dachser'), ('DPD', 'DPD'), ('DHL', 'DHL')], max_length=200, null=True, verbose_name='Spedition'),
        ),
    ]
