# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0050_auto_20180603_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickListProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Menge')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lagerplatz')),
                ('pick_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.PickList')),
                ('product_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.ProductMission')),
            ],
        ),
    ]
