# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0051_picklistproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picklist',
            name='goods_issue',
        ),
        migrations.AddField(
            model_name='picklist',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Delivery'),
        ),
    ]
