# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0053_picklistproducts_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklistproducts',
            name='missing_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fehlende Menge'),
        ),
    ]
