# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0055_picklistproducts_ignore_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picklistproducts',
            name='ignore_stock',
        ),
    ]
