# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0056_remove_picklistproducts_ignore_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreStocksPickList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lagerplatz')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Delivery')),
                ('product_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.ProductMission')),
            ],
        ),
    ]
