# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-15 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0057_ignorestockspicklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='pick_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
