# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-15 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0058_picklist_pick_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsissue',
            name='scan_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
