# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-17 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0060_packinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingListProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Menge')),
                ('missing_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Fehlende Menge')),
                ('confirmed', models.NullBooleanField(verbose_name='Bestätigt')),
                ('delivery_mission_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.DeliveryMissionProduct')),
                ('packing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.PackingList')),
            ],
        ),
    ]
