# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0061_packinglistproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglistproduct',
            name='delivery_mission_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.ProductMission'),
        ),
    ]
