# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-17 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0062_auto_20180617_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packinglistproduct',
            old_name='delivery_mission_product',
            new_name='product_mission',
        ),
    ]
