# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0065_auto_20180625_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lieferdatum'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lieferdatum'),
        ),
    ]
