# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0066_auto_20180625_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='amount_trucks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl LKWs'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='truck_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Lieferdatum'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='truck_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Lieferdatum'),
        ),
    ]
