# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0067_auto_20180627_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='amount_trucks',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='truck_date_from',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='truck_date_to',
        ),
    ]
