# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0070_truck_delivery_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Billing'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ankunftsdatum LKW'),
        ),
    ]
