# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0005_remove_employee_truck'),
        ('mission', '0071_auto_20180628_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='employees',
            field=models.ManyToManyField(to='disposition.Employee'),
        ),
    ]
