# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0072_truck_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='employees',
            field=models.ManyToManyField(blank=True, to='disposition.Employee'),
        ),
    ]
