# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0073_auto_20180628_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsissue',
            name='delivery',
        ),
    ]
