# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0075_auto_20180704_0154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsIssue',
        ),
    ]
