# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0077_auto_20180704_0222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='Partial',
        ),
    ]
