# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0079_auto_20180704_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='delivery',
            new_name='partial',
        ),
        migrations.RenameField(
            model_name='deliverymissionproduct',
            old_name='delivery',
            new_name='partial',
        ),
        migrations.RenameField(
            model_name='deliverynote',
            old_name='delivery',
            new_name='partial',
        ),
        migrations.RenameField(
            model_name='ignorestockspicklist',
            old_name='delivery',
            new_name='partial',
        ),
        migrations.RenameField(
            model_name='packinglist',
            old_name='delivery',
            new_name='partial',
        ),
        migrations.RenameField(
            model_name='picklist',
            old_name='delivery',
            new_name='partial',
        ),
    ]
