# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0080_auto_20180704_0230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryMissionProduct',
            new_name='PartialMissionProduct',
        ),
    ]
