# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0084_delivery_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lieferdatum'),
        ),
    ]
