# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0087_auto_20180704_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='billing',
            name='partial',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='partial',
        ),
    ]
