# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0088_auto_20180704_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picklist',
            name='delivery',
        ),
        migrations.AddField(
            model_name='picklist',
            name='partial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Partial'),
        ),
    ]
