# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-04 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0089_auto_20180704_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='billing',
        ),
    ]
