# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0090_remove_deliverynote_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='delivery_note',
        ),
        migrations.AddField(
            model_name='truck',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Delivery'),
        ),
    ]
