# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0091_auto_20180706_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='arrival_date',
            new_name='arrival_date_start',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='arrival_time',
            new_name='arrival_time_start',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='delivery',
        ),
    ]
