# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0092_auto_20180706_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='arrival_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Ankunftsdatum bis'),
        ),
        migrations.AddField(
            model_name='truck',
            name='arrival_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Ankunftszeit bis'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='arrival_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Ankunftsdatum von'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='arrival_time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Ankunftszeit von'),
        ),
    ]
