# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-07 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0093_auto_20180706_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='arrival_date_end',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='arrival_date_start',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='arrival_time_end',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='arrival_time_start',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='employees',
        ),
    ]
