# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-07 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0094_auto_20180707_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='outgoing',
            field=models.NullBooleanField(),
        ),
    ]
