# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-08 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0096_deliveryproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='truck_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
