# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-09 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0097_truck_truck_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partial',
            options={'ordering': ['pk']},
        ),
    ]
