# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-09 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0098_auto_20180709_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist',
            name='pick_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pick ID'),
        ),
    ]
