# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0099_auto_20180709_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Delivery'),
        ),
    ]
