# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-10 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0100_picklist_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partial',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='packinglist',
            name='picklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.PickList'),
        ),
    ]
