# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-14 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
        ('mission', '0102_auto_20180714_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online.Channel'),
        ),
    ]
