# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0103_mission_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online.Channel', verbose_name='Channel'),
        ),
    ]
