# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0104_auto_20180714_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='amazon_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
