# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0105_mission_amazon_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='amazon_order_id',
            new_name='channel_order_id',
        ),
    ]
