# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0106_auto_20180720_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_amazon_fba',
            field=models.NullBooleanField(),
        ),
    ]
