# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0107_mission_is_amazon_fba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='channel_order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fremd ID'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='is_amazon_fba',
            field=models.NullBooleanField(verbose_name='Fulfillment'),
        ),
    ]
