# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-22 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0108_auto_20180722_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmission',
            name='online_shipped_amount',
            field=models.IntegerField(default=0, verbose_name='Versendete Menge'),
        ),
    ]
