# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0110_auto_20180805_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='shipping',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL'), ('DPD', 'DPD')], max_length=200, null=True, verbose_name='Transportdienstleister'),
        ),
    ]
