# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-08 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0111_auto_20180805_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='dpd/'),
        ),
    ]
