# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-08 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0112_mission_label_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='labels/'),
        ),
    ]
