# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-15 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0114_picklistproducts_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='online_picklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.PickList', verbose_name='Online Pickauftrag'),
        ),
        migrations.AddField(
            model_name='picklist',
            name='accepted',
            field=models.NullBooleanField(verbose_name='Pickauftrag annehmen'),
        ),
    ]
