# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-16 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0116_remove_picklist_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='online_picklist',
        ),
    ]
