# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-18 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0118_mission_online_picklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='online_picklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.PickList', verbose_name='Online Pickauftrag'),
        ),
    ]
