# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-20 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0121_picklist_pick_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
