# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0122_packingstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingstation',
            name='station_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
