# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0124_auto_20180820_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingstation',
            name='station_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='packingstation',
            unique_together=set([('station_id', 'prefix')]),
        ),
    ]
