# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-20 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0125_auto_20180820_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packingstation',
            unique_together=set([('station_number', 'prefix')]),
        ),
    ]
