# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-20 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0126_auto_20180820_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packingstation',
            options={'ordering': ('prefix', 'station_number')},
        ),
    ]
