# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-20 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mission', '0127_auto_20180820_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingstation',
            name='pickorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.PickOrder'),
        ),
        migrations.AddField(
            model_name='packingstation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
