# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-21 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0128_auto_20180820_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickorder',
            name='completed',
            field=models.NullBooleanField(verbose_name='Erledigt'),
        ),
    ]
