# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-24 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0129_pickorder_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='completed',
            field=models.NullBooleanField(verbose_name='Erledigt'),
        ),
    ]
