# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-24 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0130_picklist_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklistproducts',
            name='confirmed_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bestätigte Menge'),
        ),
    ]
