# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-26 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0135_auto_20180826_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picklist',
            name='tracking_number',
        ),
    ]
