# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-28 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0136_remove_picklist_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
