# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-28 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0137_mission_purchased_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='shipped',
            field=models.NullBooleanField(verbose_name='Versendet'),
        ),
    ]
