# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-13 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0139_auto_20180906_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_online',
            field=models.NullBooleanField(choices=[(None, '----'), (True, 'Ja'), (False, 'Nein')], verbose_name='Onlinehandel'),
        ),
    ]
