# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0140_mission_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
