# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-22 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0141_mission_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='online_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Billing'),
        ),
    ]
