# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-22 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0012_auto_20180922_0119'),
        ('mission', '0142_picklist_online_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing', to='adress.Adress', verbose_name='Rechnungsadresse'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='adress.Adress', verbose_name='Lieferadresse'),
        ),
    ]
