# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-23 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0011_sku_main_sku'),
        ('mission', '0145_mission_online_transport_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productmission',
            name='product',
        ),
        migrations.AddField(
            model_name='mission',
            name='skus',
            field=models.ManyToManyField(through='mission.ProductMission', to='sku.Sku'),
        ),
        migrations.AddField(
            model_name='productmission',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sku.Sku', verbose_name='Sku'),
        ),
    ]
