# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-01 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0147_picklist_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist',
            name='online_billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.Billing'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='online_delivery_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.DeliveryNote'),
        ),
    ]
