# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-01 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0148_auto_20181101_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='not_matchable',
            field=models.NullBooleanField(verbose_name='Nicht matchbar'),
        ),
    ]
