# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-03 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0149_mission_not_matchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
