# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-04 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0153_productmission_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmission',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Rabatt'),
        ),
        migrations.AddField(
            model_name='productmission',
            name='shipping_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Rabatt für Versand'),
        ),
    ]
