# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-05 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0154_auto_20181104_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmission',
            name='brutto_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Einzelpreis (Brutto)'),
        ),
    ]
