# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0155_productmission_brutto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_amazon',
            field=models.NullBooleanField(verbose_name='Amazon'),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_ebay',
            field=models.NullBooleanField(verbose_name='Ebay'),
        ),
    ]
