# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0156_auto_20181112_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='ship_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Versanddatum von'),
        ),
        migrations.AddField(
            model_name='mission',
            name='ship_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Versanddatum bis'),
        ),
    ]
