# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disposition', '0022_remove_businessaccount_channel'),
        ('mission', '0158_productmission_no_match_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='online_business_acount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disposition.BusinessAccount', verbose_name='Geschäftskonto Transportdienstleister'),
        ),
    ]
