# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-14 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0159_mission_online_business_acount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='online_business_acount',
            new_name='online_business_account',
        ),
    ]
