# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0163_auto_20181116_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmission',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.Sku', verbose_name='Sku'),
        ),
    ]
