# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-17 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0164_auto_20181117_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='none_sku_products_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Artikel ohne SKU'),
        ),
    ]
