# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-07 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0166_mission_ignore_pickorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zustand')),
                ('ean', models.CharField(blank=True, max_length=200, null=True, verbose_name='EAN')),
                ('sku', models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Online Beschreibung')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
