# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0168_deliverynoteitem_delivery_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Menge')),
                ('state', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zustand')),
                ('ean', models.CharField(blank=True, max_length=200, null=True, verbose_name='EAN')),
                ('sku', models.CharField(blank=True, max_length=200, null=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Online Beschreibung')),
                ('netto_price', models.FloatField(blank=True, null=True, verbose_name='Einzelpreis (Netto)')),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mission.Billing')),
            ],
        ),
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Menge'),
        ),
    ]
