# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0170_auto_20181207_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmission',
            name='sku_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sku Zeichenkette'),
        ),
    ]
