# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0172_auto_20181208_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklistproducts',
            name='online_sku_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Online SKU'),
        ),
    ]
