# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0173_picklistproducts_online_sku_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmission',
            name='ean',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='EAN'),
        ),
        migrations.AddField(
            model_name='productmission',
            name='online_sku_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Online-Sku Zeichenkette'),
        ),
    ]
