# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-08 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0174_auto_20181208_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmission',
            old_name='sku_number',
            new_name='internal_sku_number',
        ),
    ]
