# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-08 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0175_auto_20181208_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmission',
            name='packing_unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Verpackungseinheit'),
        ),
    ]
