# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-10 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0177_auto_20181209_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-purchased_date']},
        ),
    ]
