# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-20 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0180_auto_20181210_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.Billing'),
        ),
        migrations.AddField(
            model_name='mission',
            name='delivery_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.DeliveryNote'),
        ),
    ]
