# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-30 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0181_auto_20181220_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping', models.CharField(blank=True, choices=[('DHL', 'DHL'), ('DPD', 'DPD')], max_length=200, null=True, verbose_name='Transportdienstleister')),
                ('label_pdf', models.FileField(blank=True, null=True, upload_to='labels/')),
            ],
        ),
    ]
