# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-30 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0182_packinglabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglabel',
            name='delivery_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.DeliveryNote'),
        ),
    ]
