# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0183_packinglabel_delivery_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packinglabel',
            old_name='shipping',
            new_name='transport_service',
        ),
    ]
