# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0184_auto_20181231_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglabel',
            name='label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='labels/', verbose_name='PDF Datei'),
        ),
        migrations.AlterField(
            model_name='packinglabel',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sendungsnummer'),
        ),
    ]
