# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0185_auto_20181231_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglabel',
            name='transport_service',
            field=models.CharField(choices=[('DHL', 'DHL'), ('DPD', 'DPD')], max_length=200, null=True, verbose_name='Transportdienstleister'),
        ),
    ]
