# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0187_auto_20181231_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglabel',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.Mission', verbose_name='Auftrag'),
        ),
    ]
