# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-01 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0188_packinglabel_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglabel',
            name='label_pdf',
            field=models.FileField(null=True, upload_to='labels/', verbose_name='PDF Datei'),
        ),
    ]
