# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-01 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0189_auto_20190101_0504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackingLabel',
            new_name='Shipment',
        ),
    ]
