# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0190_auto_20190101_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.Billing'),
        ),
    ]
