# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission', '0006_productmission_missing_amount'),
        ('order', '0042_positionproductorderpicklist_belegt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.NullBooleanField(choices=[(None, '----'), (True, 'Ja'), (False, 'Nein')])),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Mission')),
                ('productorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ProductOrder')),
            ],
        ),
    ]
