# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(blank=True, max_length=13)),
                ('anrede', models.CharField(blank=True, max_length=13)),
                ('title', models.CharField(blank=True, max_length=13)),
                ('vorname', models.CharField(blank=True, max_length=13)),
                ('nachname', models.CharField(blank=True, max_length=13)),
                ('strasse', models.CharField(blank=True, max_length=13)),
                ('hausnummer', models.CharField(blank=True, max_length=13)),
                ('adresszusatz', models.CharField(blank=True, max_length=13)),
                ('adresszusatz2', models.CharField(blank=True, max_length=13)),
            ],
        ),
    ]
