# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='adresszusatz',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adress',
            name='adresszusatz2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adress',
            name='anrede',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adress',
            name='firma',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adress',
            name='hausnummer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adress',
            name='nachname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adress',
            name='strasse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adress',
            name='vorname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
