# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0002_auto_20180421_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='zip',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
