# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0003_adress_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
