# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0004_adress_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='adresszusatz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='adresszusatz2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='anrede',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='firma',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='hausnummer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='nachname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='strasse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='title',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='vorname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='zip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
