# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0005_auto_20180501_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='adresszusatz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='adresszusatz2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='firma',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='nachname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='vorname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
