# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0006_auto_20180501_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='nachname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='vorname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
