# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-01 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0007_auto_20180501_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='adresszusatz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresszusatz'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='adresszusatz2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresszusatz 2'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='anrede',
            field=models.CharField(max_length=200, null=True, verbose_name='Anrede'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='firma',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='hausnummer',
            field=models.CharField(max_length=200, null=True, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='nachname',
            field=models.CharField(max_length=200, null=True, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='place',
            field=models.CharField(max_length=200, null=True, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='strasse',
            field=models.CharField(max_length=200, null=True, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='title',
            field=models.CharField(max_length=13, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='vorname',
            field=models.CharField(max_length=200, null=True, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='zip',
            field=models.CharField(max_length=200, null=True, verbose_name='Plz'),
        ),
    ]
