# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0008_auto_20180501_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='first_name_last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
    ]
