# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0009_adress_first_name_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='country_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ländercode'),
        ),
    ]
