# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-05 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0010_adress_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='street_and_housenumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Straße und Hasunummer'),
        ),
    ]
