# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-21 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0011_adress_street_and_housenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresslinie 1'),
        ),
        migrations.AddField(
            model_name='adress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresslinie 2'),
        ),
        migrations.AddField(
            model_name='adress',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresslinie 3'),
        ),
    ]
