# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='volumen',
            field=models.FloatField(blank=True, default='100.0'),
        ),
    ]
