# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
        ('column', '0002_auto_20171226_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='positions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='position.Position'),
        ),
    ]
