# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
        ('column', '0005_columnposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='positions',
            field=models.ManyToManyField(through='column.ColumnPosition', to='position.Position'),
        ),
    ]
