# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('column', '0007_remove_column_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnposition',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='columnposition',
            name='positions',
        ),
        migrations.DeleteModel(
            name='ColumnPosition',
        ),
    ]
