# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-29 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('column', '0009_auto_20171228_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnposition',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='columnposition',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='column',
            name='positions',
        ),
        migrations.DeleteModel(
            name='ColumnPosition',
        ),
    ]
