# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0011_auto_20180316_1659'),
        ('product', '0001_initial'),
        ('invoice', '0002_remove_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.CharField(max_length=13)),
                ('extra_text', models.CharField(max_length=13)),
                ('terms_of_payment', models.CharField(max_length=13)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(blank=True, max_length=13, verbose_name='Bestellnummer')),
                ('delivery_date', models.DateField(default=datetime.date.today, verbose_name='Lieferdatum')),
                ('status', models.CharField(blank=True, default='OFFEN', max_length=25, null=True, verbose_name='Status')),
                ('verified', models.NullBooleanField(choices=[(None, '----'), (True, 'Ja'), (False, 'Nein')], verbose_name='Akzeptiert')),
                ('invoice', models.ManyToManyField(through='order.InvoiceOrder', to='invoice.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Menge')),
                ('missing_amount', models.IntegerField(blank=True, null=True, verbose_name='Fehlende Menge')),
                ('netto_price', models.FloatField(blank=True, null=True, verbose_name='Einzelpreis (Netto)')),
                ('confirmed', models.NullBooleanField(verbose_name='Bestätigt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Artikel')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='order.ProductOrder', to='product.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='supplier.Supplier', verbose_name='Lieferant'),
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceorder',
            unique_together=set([('invoice', 'order')]),
        ),
    ]
