# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 8, 53, 52, 836485)),
        ),
    ]
