# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0007_auto_20171214_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
