# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20171214_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
