# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('invoice', '0001_initial'),
        ('order', '0010_auto_20171220_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='invoice.Invoice'),
        ),
    ]
