# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0011_order_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoices',
        ),
    ]
