# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_date'),
        ('order', '0012_remove_order_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.CharField(max_length=13)),
                ('extra_text', models.CharField(max_length=13)),
                ('terms_of_payment', models.CharField(max_length=13)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ManyToManyField(through='order.InvoiceOrder', to='invoice.Invoice'),
        ),
    ]
