# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20171230_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceorder',
            old_name='order',
            new_name='order_invoice',
        ),
    ]
