# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0014_auto_20171230_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceorder',
            old_name='order_invoice',
            new_name='order',
        ),
    ]
