# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0017_auto_20171230_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
    ]
