# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('supplier', '0007_remove_supplier_contact'),
        ('order', '0018_remove_order_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='supplier.Supplier'),
        ),
    ]
