# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-31 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0021_auto_20171231_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceorder',
            old_name='datum',
            new_name='invoice_date',
        ),
    ]
