# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-31 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20171231_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceorder',
            old_name='invoice_date',
            new_name='datum',
        ),
    ]
