# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-31 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_date'),
        ('order', '0025_auto_20171231_0347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceorder',
            unique_together=set([('invoice', 'order')]),
        ),
    ]
