# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20171231_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='OFFEN', max_length=25, null=True),
        ),
    ]
