# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20180113_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verified',
            field=models.NullBooleanField(),
        ),
    ]
