# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_order_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='verified',
            field=models.NullBooleanField(choices=[(None, '----'), (True, 'Ja'), (False, 'Nein')]),
        ),
    ]
