# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_positionproductorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionproductorder',
            name='positions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='position.Position'),
        ),
        migrations.AlterField(
            model_name='positionproductorder',
            name='status',
            field=models.NullBooleanField(choices=[(None, '----'), (True, 'Position'), (False, 'WE')]),
        ),
    ]
