# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picklist', '0001_initial'),
        ('order', '0039_auto_20180125_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionProductOrderPicklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=13)),
                ('pickerid', models.CharField(max_length=13)),
                ('picklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picklist.Picklist')),
                ('positionproductorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.PositionProductOrder')),
            ],
        ),
    ]
