# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_positionproductorderpicklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionproductorderpicklist',
            name='picklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artikeln', to='picklist.Picklist'),
        ),
        migrations.AlterField(
            model_name='positionproductorderpicklist',
            name='positionproductorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positionsproduct', to='order.PositionProductOrder'),
        ),
    ]
