# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_auto_20180308_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='netto_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Preis (Netto)'),
        ),
    ]
