# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_productorder_netto_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='confirmed',
            field=models.NullBooleanField(verbose_name='Bestätigt'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='missing_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fehlende Menge'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='netto_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Einzelpreis (Netto)'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Artikel'),
        ),
    ]
