# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_auto_20180316_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionproductorder',
            name='productorder',
        ),
    ]
