# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-23 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adress.Adress', verbose_name='Lieferadresse'),
        ),
    ]
