# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-29 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_main_image'),
        ('order', '0054_auto_20180429_1916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together=set([('order', 'product')]),
        ),
    ]
