# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-03 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_auto_20180429_1921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together=set([]),
        ),
    ]
