# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0057_auto_20180506_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_costs',
            field=models.FloatField(blank=True, null=True, verbose_name='Transportkosten'),
        ),
    ]
